### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sriharshaguthikonda** [KruxAI/ragbuilder#30]
With Lil bit of tinkering ollama works, I hope?

**Comment by ashwinzyx** [comment]
Please provide the OLLAMA_BASE_URL in the .env file and OLLAMA supported models should work. If you are using docker for RAGbuilder you need to give http://host.docker.internal:11434 instead. 

OLLAMA_BASE_URL=http://localhost:11434 #http://host.docker.internal:11434/

**Comment by sriharshaguthikonda** [comment]
tq . got it.!
