### ISSUE TITLE
Error with docker-compose.yml

### ISSUE THREAD

**Issue by phren0logy** [KruxAI/ragbuilder#41]
Aplogies if this quesiton is overly basic, but I grabbed the docker-compose.yml file and ran it, resulting in the following error:

`WARN[0000] /Users/andy/RAGBuilder/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Building 0.0s (0/0)
unable to prepare context: path "/Users/andy/RAGBuilder/neo4j" not found`

Creating a neo4j folder does not help. Thanks.

**Comment by ashwinzyx** [comment]
Could you try cloning the whole repo
